sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t docker-react-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-travis  npm run test  -- --coverage
