name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"

        # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
